name: "Team's Workflow"

on:
  pull_request:
    types: [opened, edited, closed, reopened, labeled, unlabeled]
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 22 * * 1-5"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr_commented:
    name: "PR Comment"
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "A comment was made on PR #${{ github.event.issue.number }} by ${{ github.actor }}"

  issue_commented:
    name: "Issue Comment"
    if: ${{ github.event_name == 'issue_comment' && !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "A comment was made on issue #${{ github.event.issue.number }} by ${{ github.actor }}"

  test_schedule:
    name: "Test Schedule"
    runs-on: ubuntu-latest
    steps:
      - name: Test Cron Job
        run: echo "Cron job executed at $(date)"
