name: "Team's Workflow"

on:
  pull_request:
    types: [deleted, opened, converted_to_draft, unassigned, labeled, unlabeled, edited, closed, synchronize, reopened]
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 22 * * 1-5"
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read
  deployments: read
  id-token: none
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  security-events: read
  statuses: write

jobs:
  pr_commented:
    name: "PR Comment"
    # Runs when an issue comment is created on a pull request
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request != null }}
    runs-on: windows-latest
    steps:
      - name: Log PR Comment
        run: echo "A comment was made on PR #${{ github.event.issue.number }} by ${{ github.actor }}"

  issue_commented:
    name: "Issue Comment"
    # Runs when an issue comment is created on an issue
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request == null }}
    runs-on: windows-latest
    steps:
      - name: Log Issue Comment
        run: echo "A comment was made on issue #${{ github.event.issue.number }} by ${{ github.actor }}"

  test_schedule:
    name: "Test Schedule"
    # Runs at the specified cron schedule
    runs-on: windows-latest
    steps:
      # Check if it's Wednesday and skip if true
      - name: Skip on Wednesday
        run: |
          if [ "$(date +%u)" -eq 3 ]; then
            echo "Skipping because it's Wednesday."
            exit 0
          fi
          echo "Running because it's not Wednesday."

      # This step runs regardless of the day
      - name: Always Run
        run: echo "Cron job executed at $(date)"
